import React from 'react'

export default function Play(props) {
    return (
        <div id="play-wrapper">
            <div className={props.animation} >
                <h1 style={{ marginTop: "20px" }}>This page brought to you by </h1>
                <h1><a href="https://phbquick.com" alt="phb quick" target="_blank" rel="noopener noreferrer"><emphasis>PHB Quick</emphasis></a></h1>
                <div className="">A free player handbook reference guide for Dungeons and Dragons, 5th edition.  (personal project, in beta)</div>
                <div className="" style={{ color: 'gold' }}>More content coming soon!</div>
                <h3>I have a lot of hobbies.</h3>
            </div>
            <div id="fine-print">Headshots by <a href="https://www.leepeters.com/"><emphasis>Lee Peters</emphasis></a><br />SVG art generated by <a href="https://www.svgbackgrounds.com/" alt="phb quick" target="_blank" rel="noopener noreferrer"><emphasis>svgbackgrounds</emphasis></a><br /></div>

        </div>
    )
}
